### ISSUE TITLE
Problem when trying to run predict_bb.py, Please if you went through the same error can you let me know how to solve it? Than you in advance

### ISSUE THREAD

**Issue by dukezacks** [lmb-freiburg/FreiPose-docker#5]
`Predicting:   0%|                                                            | 0/360 [00:00<?, ?it/s]2022-10-14 08:09:21.139068: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2022-10-14 08:09:21.147188: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Predicting:   0%|                                                            | 0/360 [16:51<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D}}]]
	 [[{{node detection_boxes}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict_bb.py", line 138, in <module>
    feed_dict={input_tensors['image_tensor']: imgs})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D (defined at /home/duke/FreiPose/utils/detector_util.py:20) ]]
	 [[node detection_boxes (defined at /home/duke/FreiPose/utils/detector_util.py:20) ]]

Caused by op 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D', defined at:
  File "predict_bb.py", line 114, in <module>
    sess, input_tensors, pred_tensors = load_inference_graph(model.bb_models[-1])
  File "/home/duke/FreiPose/utils/detector_util.py", line 20, in load_inference_graph
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D (defined at /home/duke/FreiPose/utils/detector_util.py:20) ]]
	 [[node detection_boxes (defined at /home/duke/FreiPose/utils/detector_util.py:20) ]]
`

**Comment by arturoptophys** [comment]
Hi,
this seems to be a cuDNN related issue.  
Are you running the code from inside the Docker-container? Please make sure you have a working CUDA and cuDNN installation.  Furthermore, make sure your GPU has enough memory left.

Best,
Artur

**Comment by dukezacks** [comment]
Thank you for the reply. Yes i am running the code from the Docker container and my Cuda and cuDNN are perfectly installed but i get the same error 

Ubuntu: 20.04
10.0-cudnn7-runtime-ubuntu18.04

**Comment by arturoptophys** [comment]
Hmm.. seems to be a memory allocation problem. 
What is your output from **nvidia-smi** ?

You could try adding 
> config = tf.ConfigProto()
> config.gpu_options.allow_growth = True

to /utils/detector_util.py after tf import.. 

and adding config=config to 
> sess = tf.Session(graph=detection_graph,config=config)

Good luck,
Artur

**Comment by dukezacks** [comment]
![nvidia-smi](https://user-images.githubusercontent.com/106013071/195810733-2905e4bd-07f1-4061-899e-bae734a40bd8.png)

**Comment by dukezacks** [comment]
Thank you for you help this problem is solved, but i used different way to solve it. At first i tried the container wasn't working and i thought it will be OK to create my own Anaconda env and was able to solve the problem.
 @arturoptophys  thank you for your help 
@arturoptophys  can you let me know your email i want to ask something if you don't mind.

Yours Duke.

**Comment by arturoptophys** [comment]
Happy to hear the issue was solved.
@DukeMacrocat artur.schneider@biologie.uni-freiburg.de

Best,
Artur
